.PHONY: clean All

All:
	@echo "----------Building project:[ DS_Practice2 - Debug ]----------"
	@cd "DS_Practice2" && "$(MAKE)" -f  "DS_Practice2.mk"
clean:
	@echo "----------Cleaning project:[ DS_Practice2 - Debug ]----------"
	@cd "DS_Practice2" && "$(MAKE)" -f  "DS_Practice2.mk" clean
